CREATE DATABASE VENERE;

CREATE TABLE UTENTE(
    NOMEUTENTE VARCHAR(255) PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255),
    NOME VARCHAR(255),
    COGNOME VARCHAR(255)
)ENGINE = InnoDB;

ALTER TABLE UTENTE ADD TIPOUTENTE ENUM{'MOD', 'USER'} DEFAULT 'USER';

ALTER TABLE UTENTE ADD STATO ENUM{'ATTIVO', 'SOSPESO', 'BANNATO'} DEFAULT 'ATTIVO';

CREATE TABLE CATEGORIADINTERESSE(
    IDCATEGORIA INT PRIMARY KEY,
    NOME VARCHAR(255)	
)ENGINE = InnoDB;

CREATE TABLE PREFERENZA(
    UTENTE VARCHAR(255),
    IDCAT INT,
    PRIMARY KEY(UTENTE, IDCAT),
    FOREIGN KEY (UTENTE) REFERENCES UTENTE(NOMEUTENTE),
    FOREIGN KEY (IDCAT) REFERENCES CATEGORIADINTERESSE(IDCATEGORIA)
)ENGINE = InnoDB;

CREATE TABLE EVENTO(
    IDEVENTO AUTO_INCREMENT PRIMARY KEY,
    TITOLO VARCHAR(255),
    DATAEVENTO DATE,
    ORAEVENTO TIME,
    LUOGO VARCHAR(255),
    CATEGORIA VARCHAR(255),
    DESCRIZIONE VARCHAR(255),
    SITO VARCHAR(255),
    IMMAGINE VARCHAR(255),
    STATO ENUM{'ATTESA', 'ACCETTATO'} DEFAULT 'ATTESA',
    FOREIGN KEY(CATEGORIA) REFERENCES CATEGORIADINTERESSE(ID)
)ENGINE =  InnoDB;


CREATE TABLE COMMENTO(
    IDCOMMENTO INT PRIMARY KEY,
    CODICEEVENTO INT,
    NOMEU VARCHAR(255),
    TESTO VARCHAR(255),
    VOTO INT,
    STATO ENUM{'ATTESA', 'ACCETTATO'} DEFAULT 'ATTESA',
    FOREIGN KEY(CODICEEVENTO) REFERENCES EVENTO(IDEVENTO),
    FOREIGN KEY(NOMEU) REFERENCES UTENTE(NOMEUTENTE)
)ENGINE = InnoDB;


CREATE TABLE ARTISTA(
    IDARTISTA INT PRIMARY KEY,
    NOME VARCHAR(255),
    COGNOME VARCHAR(255)
)ENGINE = InnoDB;

CREATE TABLE PARTECIPAZIONE(
    CODEVENTO INT,
    IDART INT,
    PRIMARY KEY(CODEVENTO, IDART),
    FOREIGN KEY(CODEVENTO) REFERENCES EVENTO(IDEVENTO),
    FOREIGN KEY(IDART) REFERENCES ARTISTA(IDARTISTA)
)ENGINE = InnoDB;